// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebServer.Models;

namespace Server.Migrations
{
    [DbContext(typeof(NotesContext))]
    [Migration("20210329202953_V1")]
    partial class V1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebServer.Models.Beleska", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("DogadjajID")
                        .HasColumnType("int");

                    b.Property<int?>("NotesID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("DogadjajID");

                    b.HasIndex("NotesID");

                    b.ToTable("Beleska");
                });

            modelBuilder.Entity("WebServer.Models.Dogadjaj", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Dan")
                        .HasColumnType("int")
                        .HasColumnName("Dan");

                    b.Property<string>("Ime_dogadjaja")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Ime");

                    b.Property<int>("Mesec")
                        .HasColumnType("int")
                        .HasColumnName("Mesec");

                    b.Property<string>("Opis_dogadjaja")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Opis");

                    b.Property<int>("Prioritet")
                        .HasColumnType("int")
                        .HasColumnName("Prioritet");

                    b.HasKey("ID");

                    b.ToTable("Dogadjaj");
                });

            modelBuilder.Entity("WebServer.Models.Notes", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Broj_kolona")
                        .HasColumnType("int")
                        .HasColumnName("Kolona");

                    b.Property<int>("Broj_redova")
                        .HasColumnType("int")
                        .HasColumnName("Red");

                    b.Property<string>("Ime_notesa")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Ime");

                    b.HasKey("ID");

                    b.ToTable("Notes");
                });

            modelBuilder.Entity("WebServer.Models.Beleska", b =>
                {
                    b.HasOne("WebServer.Models.Dogadjaj", "Dogadjaj")
                        .WithMany()
                        .HasForeignKey("DogadjajID");

                    b.HasOne("WebServer.Models.Notes", "Notes")
                        .WithMany("Beleske")
                        .HasForeignKey("NotesID");

                    b.Navigation("Dogadjaj");

                    b.Navigation("Notes");
                });

            modelBuilder.Entity("WebServer.Models.Notes", b =>
                {
                    b.Navigation("Beleske");
                });
#pragma warning restore 612, 618
        }
    }
}
